# Defaults tasks for role odcs-frontend

---

- name: install the EPEL packages required for ODCS backend
  package:
    name: "epel-release"
    state: present
  tags:
  - odcs

- name: Use the Fedora infra repo
  copy:
    src: infrastructure.repo
    dest: /etc/yum.repos.d/infrastructure.repo
    mode: 0644
    owner: root
    group: root

- name: install the packages required for ODCS
  package:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - odcs
    - mod_auth_gssapi
    - mod_wsgi
    - mod_ssl
    - python3-qpid-proton
    - fedora-messaging
    - python3-psycopg2
  tags:
  - odcs

- name: install the latest ODCS package
  package:
    name: odcs
    state: latest
    update_cache: yes
  when: odcs_upgrade
  notify:
  - restart httpd service
  tags:
  - odcs

- include_role:
    name: httpd
  vars:
    - httpd_tls: True

########
# Need to add the messaging part

- name: modify selinux so that httpd can serve data from NFS shares if needed
  seboolean: 
    name: httpd_use_nfs
    state: yes
    persistent: yes
  when: "'enabled' in ansible_selinux.status"
  tags:
  - odcs

- name: create odcs-server group
  group:
    name: odcs-server
    gid: 64321
    state: present
 
- name: create odcs-server user
  user:
    name: odcs-server
    uid: 64321
    group: odcs-server

- name: Add apache user to odcs-server group.	
  user:	
    name: apache	
    groups: odcs-server	
    append: yes

- name: create ODCS_TARGET_DIR
  file:
    path: "{{ odcs_target_dir }}"
    state: directory
    owner: odcs-server
    group: odcs-server
    mode: 0775
  tags:
  - odcs

- name: generate the ODCS app config
  template:
    src: etc/odcs/config.py.j2
    dest: /etc/odcs/config.py
    owner: odcs-server
    group: odcs-server
    mode: 0440
  notify:
  - reload httpd service
  tags:
  - odcs

- name: generate the ODCS Apache config
  template:
    src: etc/httpd/conf.d/odcs.conf.j2
    dest: /etc/httpd/conf.d/odcs.conf
    owner: apache
    group: apache
    mode: 0440
  notify:
  - reload httpd service
  tags:
  - odcs

- name: copy the odcs rabbitmq private queue crt.
  copy:
    src: "{{pkistore}}/rabbitmq-private/centos-odcs-private-queue.crt"
    dest: /etc/odcs/odcs-private-queue.crt
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq private queue key.
  copy:
    src: "{{pkistore}}/rabbitmq-private/centos-odcs-private-queue.key"
    dest: /etc/odcs/odcs-private-queue.key
    owner: odcs-server
    mode: 0640
  tags:
  - odcs

- name: copy the odcs rabbitmq crt.
  copy:
    src: "{{pkistore}}/fedora-messaging/odcs/centos-odcs.crt"
    dest: /etc/odcs/odcs-rabbitmq.crt
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq key.
  copy:
    src: "{{pkistore}}/fedora-messaging/odcs/centos-odcs.key"
    dest: /etc/odcs/odcs-rabbitmq.key
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq CA cert.
  copy:
    src: "{{pkistore}}/fedora-messaging/ca.crt"
    dest: /etc/odcs/ca.crt
    owner: odcs-server
    group: apache
    mode: 0640
  tags:
  - odcs

- name: generate the fedora-messaging config
  template:
    src: fedora-messaging.toml.j2
    dest: /etc/fedora-messaging/config.toml
    owner: root
    group: root
    mode: 0644
  tags:
  - odcs

- name: install the http keytab
  copy:
    src: "{{pkistore}}/odcs/http-{{ odcs_frontend_hostname }}"
    dest: "/etc/httpd/conf/http-{{ odcs_frontend_hostname }}.keytab"
    owner: apache
    group: apache
    mode: 0440
  when: odcs_auth_backend == "kerberos" or odcs_auth_backend == "kerberos_or_ssl"
  notify:
  - reload httpd service
  tags:
  - odcs

- name: install the httpd TLS cert
  copy:
    src: "{{pkistore}}/{{ odcs_frontend_hostname }}.crt"
    dest: "/etc/pki/tls/certs/{{ odcs_frontend_hostname }}.crt"
    owner: apache
    group: apache
    mode: 0440
  notify:
  - reload httpd service
  tags:
  - odcs

- name: install the httpd TLS key
  copy:
    src: "{{pkistore}}/{{ odcs_frontend_hostname }}.key"
    dest: "/etc/pki/tls/private/{{ odcs_frontend_hostname }}.key"
    owner: apache
    group: apache
    mode: 0440
  notify:
  - reload httpd service
  tags:
  - odcs

- name: install any CAs
  copy:
    src: "{{pkistore}}/{{ odcs_frontend_ca_crt}}"
    dest: "/etc/pki/tls/certs/{{ odcs_frontend_ca_crt }}"
    owner: apache
    group: apache
    mode: 0440
  notify:
  - reload httpd service
  tags:
  - odcs

- name: Disable PrivateTmp=true in httpd.service.
  lineinfile:
    path: /usr/lib/systemd/system/httpd.service
    regexp: '^PrivateTmp'
    line: 'PrivateTmp=false'
  notify:
  - reload systemd
  - restart httpd service
  tags:
  - odcs

- name: start ODCS frontend
  systemd:
    name: httpd
    state: started
  tags:
  - odcs
