# Defaults handlers for role odcs-frontend

- name: reload systemd
  command: systemctl daemon-reload

- name: restart httpd service
  command: /usr/local/bin/conditional-restart.sh httpd httpd

- name: reload httpd service
  action: service name=httpd state=reloaded
