# Defaults handlers for role odcs-frontend

- name: reload systemd
  command: systemctl daemon-reload

- name: restart httpd service
  action: service name=httpd state=restarted

- name: reload httpd service
  action: service name=httpd state=reloaded
