# Defaults handlers for role odcs-frontend

- name: reload systemd
  command: systemctl daemon-reload

- name: restart httpd service
  action: service name=httpd state=restarted

- name: reload httpd service
  action: service name=httpd state=reloaded

- name: restart_odcs_celery_cleanup
  service:
    name: odcs-celery-cleanup
    state: restarted
